[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.shell]
command = "shfmt"
options = ["-w"]
includes = ["*.sh"]

[formatter.lua]
command = "stylua"
includes = ["*.lua"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.json", "*.yaml", "*.yml", "*.md"]

[formatter.python]
command = "black"
includes = ["*.py"]
