enable_cache = true
debug = false

[templates]
default = "{album.artist}/{album.date:%Y}. {album.title}/Disc {item.volume}/{item.number:02d}. {item.title}"
track = "{album.artist}/{album.date:%Y}. {album.title}/Disc {item.volume}/{item.number:02d}. {item.title}"
video = "{album.artist}/videos/{item.artist}/{item.artist} - {item.title}"
album = "{album.artist}/{album.date:%Y}. {album.title}/Disc {item.volume}/{item.number:02d}. {item.title}"
playlist = "playlists/{playlist.title}/{playlist.index:02d}. {item.artist} - {item.title_version}"
mix = "mixes/{playlist.title}/{playlist.index:02d}. {item.artist} - {item.title_version}"

[download]
track_quality = "high"
video_quality = "fhd"
skip_existing = true
threads_count = 4
download_path = "/music"
scan_path = "/music"
singles_filter = "none"
videos_filter = "none"
update_mtime = false
rewrite_metadata = false

[metadata]
enable = true
lyrics = true
cover = true

[cover]
save = true
size = 1280
allowed = ["album"]

[cover.templates]
album = "{album.artist}/{album.date:%Y}. {album.title}/cover"

[m3u]
save = true
allowed = ["mix", "playlist"]

[m3u.templates]
album = "m3u/{type}/{album.artist} - {album.title}"
playlist = "m3u/{type}/{playlist.title}"
mix = "m3u/{type}/{now:%x}"
